/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Version 1 interchange contract, including optional CPU structure sampling and constrained optimization. Runtime validation checks dimensions, references and feasibility. Uint8ClampedArray is an in-memory image adapter.
 */
export type BeadifyContracts =
  GenerationRequestJson | BeadPattern | Palette | Bom | SourceRaster | TextAnalysis | SceneAnalysis;
export type ColorId = string;
/**
 * @minItems 3
 * @maxItems 3
 */
export type Srgb8 = [number, number, number];

export interface GenerationRequestJson {
  schemaVersion: 1;
  revision: number;
  image: RgbaImageJson;
  width: number;
  height: number;
  palette: Palette;
  method: "nearest" | "area" | "dominant" | "optimized";
  maxColors: number;
  /**
   * @minItems 1
   * @maxItems 512
   */
  allowedColors?: [ColorId, ...ColorId[]];
  preprocessing?: PreprocessingOptions;
  style?: "accurate" | "clean" | "pixel-art" | "pixel-input";
  /**
   * @minItems 0
   * @maxItems 1024
   */
  constraints?: CellConstraint[];
  /**
   * @minItems 0
   * @maxItems 512
   */
  requiredColors?: ColorId[];
  optimization?: OptimizationOptions;
  /**
   * @minItems 2
   * @maxItems 2
   */
  phase?: [number, number];
  sampling?: SamplingOptions;
  /**
   * @minItems 0
   * @maxItems 128
   */
  sourceFeatures?: SourceFeatureRegion[];
  preparedRaster?: SourceRaster;
}
export interface RgbaImageJson {
  width: number;
  height: number;
  /**
   * @maxItems 16777216
   */
  data: number[];
}
export interface Palette {
  id: string;
  version: string;
  source: string;
  license: string;
  approximate: boolean;
  /**
   * @minItems 1
   * @maxItems 512
   */
  colors: [PaletteColor, ...PaletteColor[]];
}
export interface PaletteColor {
  id: ColorId;
  brand: string;
  series: string;
  code: string;
  name?: string;
  srgb8: Srgb8;
}
export interface PreprocessingOptions {
  /**
   * @minItems 4
   * @maxItems 4
   */
  crop?: [number, number, number, number];
  background?: "keep" | "edge";
  tolerance?: number;
  /**
   * @minItems 0
   * @maxItems 4194304
   */
  mask?: number[];
  smoothing?: boolean;
}
export interface CellConstraint {
  kind: "lock-color" | "lock-empty" | "protect" | "simplify" | "feature";
  /**
   * @minItems 1
   * @maxItems 65536
   */
  cellIndices: [number, ...number[]];
  colorId?: ColorId;
  strength?: number;
  /**
   * @minItems 1
   * @maxItems 512
   */
  colorIds?: [ColorId, ...ColorId[]];
  minCells?: number;
  allowSingleton?: boolean;
}
export interface OptimizationOptions {
  iterations?: number;
  maxEvaluations?: number;
  symmetry?: boolean;
  restarts?: number;
  seed?: number;
  weights?: EnergyWeightOptions;
  islandMaxSize?: number;
  unary?: "representative" | "modes";
  /**
   * Use bounded soft existence constraints from original compact and thin connected components; false disables only these automatic groups for ablation.
   */
  sourceComponents?: boolean;
  /**
   * Use source-supported path, endpoint and interior shape conditions.
   */
  sourceShapes?: boolean;
  /**
   * Prioritize representable chromatic source regions within the hard palette budget.
   */
  sourceColors?: boolean;
}
export interface EnergyWeightOptions {
  color?: number;
  smooth?: number;
  edge?: number;
  island?: number;
  palette?: number;
  feature?: number;
  symmetry?: number;
}
export interface SamplingOptions {
  strategy?: "dominant" | "mean" | "weighted-area" | "modes";
  sourceEdges?: boolean;
  /**
   * Use source color and direction continuity to join strokes across color bins; false retains exact-bin evidence.
   */
  crossBinStrokes?: boolean;
}
export interface SourceFeatureRegion {
  id: string;
  label: string;
  mask: SourceFeatureMask;
  /**
   * @minItems 1
   * @maxItems 512
   */
  colorIds: [ColorId, ...ColorId[]];
  minCells: number;
  importance: number;
  confidence: number;
  allowSingleton: boolean;
}
export interface SourceFeatureMask {
  width: number;
  height: number;
  /**
   * @minItems 1
   * @maxItems 262144
   */
  runs: [[number, number], ...[number, number][]];
}
export interface SourceRaster {
  schemaVersion: 1;
  width: number;
  height: number;
  frameWidth: number;
  frameHeight: number;
  geometry: PatternGeometry;
  sourceHash: string;
  inputHash: string;
  configHash: string;
  /**
   * @minItems 1
   * @maxItems 65536
   */
  cells: [RasterCell | null, ...(RasterCell | null)[]];
  /**
   * @minItems 0
   * @maxItems 1024
   */
  features: CellConstraint[];
  /**
   * @minItems 0
   * @maxItems 128
   */
  warnings: string[];
  sampling?: SamplingOptions;
  algorithmVersion?: number;
}
export interface PatternGeometry {
  sourceWidth: number;
  sourceHeight: number;
  fit: "contain";
  /**
   * @minItems 9
   * @maxItems 9
   */
  sourceToGrid: [number, number, number, number, number, number, number, number, number];
  alphaCoverageThreshold: 0.5;
  /**
   * @minItems 4
   * @maxItems 4
   */
  crop?: [number, number, number, number];
  /**
   * @minItems 2
   * @maxItems 2
   */
  phase?: [number, number];
  frameWidth?: number;
  frameHeight?: number;
}
export interface RasterCell {
  coverage: number;
  mean: RasterColor;
  representative: RasterColor;
  /**
   * @minItems 1
   * @maxItems 16
   */
  modes:
    | [RasterMode]
    | [RasterMode, RasterMode]
    | [RasterMode, RasterMode, RasterMode]
    | [RasterMode, RasterMode, RasterMode, RasterMode]
    | [RasterMode, RasterMode, RasterMode, RasterMode, RasterMode]
    | [RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode]
    | [RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode]
    | [RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode]
    | [RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode, RasterMode]
    | [
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode
      ]
    | [
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode
      ]
    | [
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode
      ]
    | [
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode
      ]
    | [
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode
      ]
    | [
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode
      ]
    | [
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode,
        RasterMode
      ];
  edge: number;
  importance: number;
  sourceMean?: RasterColor;
  weightedMean?: RasterColor;
  sourceEdge?: number;
  sourceContrast?: number;
  edgeReliability?: number;
  samplingStrategy?: "dominant" | "mean" | "weighted-area" | "modes";
  sourceRightContrast?: number;
  sourceRightReliability?: number;
  sourceDownContrast?: number;
  sourceDownReliability?: number;
  sourceDominance?: number;
}
export interface RasterColor {
  space: "oklab";
  L: number;
  a: number;
  b: number;
}
export interface RasterMode {
  color: RasterColor;
  weight: number;
  sourceWeight?: number;
  structuralSupport?: number;
  sourceContrast?: number;
  boundarySupport?: number;
  compactSupport?: number;
  /**
   * @maxItems 2
   */
  components?: [] | [SourceComponentEvidence] | [SourceComponentEvidence, SourceComponentEvidence];
}
export interface SourceComponentEvidence {
  id: number;
  coverage: number;
  support: number;
  kind: "compact" | "stroke" | "region";
  span: number;
  endpointMask?: number;
  closed?: boolean;
  thickness?: number;
  contrast?: number;
}
export interface BeadPattern {
  schemaVersion: 1;
  width: number;
  height: number;
  /**
   * @maxItems 65536
   */
  cells: (ColorId | null)[];
  paletteHash: string;
  paletteSnapshot: Palette;
  inputRevision: number;
  configHash: string;
  geometry: PatternGeometry;
  diagnostics: PatternDiagnostics;
}
export interface PatternDiagnostics {
  usedColors: number;
  physicalComponents: number;
  monochromeSingletons: number;
  colorReduction: "none" | "frequency-subpalette" | "optimized-subpalette";
  /**
   * @maxItems 32
   */
  warnings: string[];
  optimization?: OptimizationReport;
  diagonalContacts?: number;
  narrowConnections?: number;
  sampling?: {
    multimodalCells: number;
    minorityCandidates: number;
  };
}
export interface OptimizationReport {
  preset: "accurate" | "clean" | "pixel-art";
  initialEnergy: number;
  finalEnergy: number;
  terms: EnergyTerms;
  iterations: number;
  evaluations: number;
  stopReason: "converged" | "iteration-budget" | "evaluation-budget" | "empty";
  /**
   * @minItems 0
   * @maxItems 1000
   */
  trace: number[];
  hardConstraintsSatisfied: true;
  /**
   * @minItems 1
   * @maxItems 8
   */
  runs?:
    | [OptimizationRun]
    | [OptimizationRun, OptimizationRun]
    | [OptimizationRun, OptimizationRun, OptimizationRun]
    | [OptimizationRun, OptimizationRun, OptimizationRun, OptimizationRun]
    | [OptimizationRun, OptimizationRun, OptimizationRun, OptimizationRun, OptimizationRun]
    | [OptimizationRun, OptimizationRun, OptimizationRun, OptimizationRun, OptimizationRun, OptimizationRun]
    | [
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun
      ]
    | [
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun,
        OptimizationRun
      ];
  seed?: number;
  bestRun?: number;
}
export interface EnergyTerms {
  color: number;
  smooth: number;
  edge: number;
  island: number;
  palette: number;
  feature: number;
  symmetry: number;
  total: number;
}
export interface OptimizationRun {
  initialization: string;
  initialEnergy: number;
  finalEnergy: number;
  evaluations: number;
  iterations: number;
  stopReason: "converged" | "iteration-budget" | "evaluation-budget" | "empty";
  /**
   * @minItems 0
   * @maxItems 1000
   */
  trace?: number[];
}
export interface Bom {
  schemaVersion: 1;
  paletteHash: string;
  totalBeads: number;
  /**
   * @maxItems 512
   */
  rows: BomRow[];
}
export interface BomRow {
  colorId: ColorId;
  brand: string;
  series: string;
  code: string;
  srgb8: Srgb8;
  count: number;
}
export interface TextAnalysis {
  schemaVersion: 1;
  kind: "text-analysis";
  source: TextSource;
  provider: TextProvider;
  /**
   * @minItems 0
   * @maxItems 128
   */
  regions: TextRegion[];
  /**
   * @minItems 0
   * @maxItems 128
   */
  suggestions: TextSuggestion[];
  /**
   * @minItems 0
   * @maxItems 128
   */
  corrections: TextCorrection[];
  /**
   * @minItems 0
   * @maxItems 128
   */
  evidence: TextEvidence[];
  /**
   * @minItems 0
   * @maxItems 128
   */
  relations: TextRelation[];
  rawOutput: string;
  cacheKey: string;
  contentHash: string;
}
export interface TextSource {
  rgbaHash: string;
  width: number;
  height: number;
  analysisWidth: number;
  analysisHeight: number;
  /**
   * @minItems 9
   * @maxItems 9
   */
  sourceToAnalysis: [number, number, number, number, number, number, number, number, number];
  /**
   * @minItems 9
   * @maxItems 9
   */
  analysisToSource: [number, number, number, number, number, number, number, number, number];
  preprocessingHash: string;
}
export interface TextProvider {
  kind: "none" | "fixture" | "manual" | "ocr" | "vlm";
  id: string;
  version: string;
  modelHash: string | null;
  configHash: string;
  promptHash: string | null;
  device: string;
}
export interface TextRegion {
  id: string;
  parentId: string | null;
  /**
   * @minItems 3
   * @maxItems 16
   */
  polygon:
    | [[number, number], [number, number], [number, number]]
    | [[number, number], [number, number], [number, number], [number, number]]
    | [[number, number], [number, number], [number, number], [number, number], [number, number]]
    | [[number, number], [number, number], [number, number], [number, number], [number, number], [number, number]]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ];
  granularity: "line" | "word" | "character" | "unknown";
  role: "text" | "logo" | "watermark" | "artwork" | "unknown";
  status: "verified" | "unverified" | "unknown";
  transcription: string;
  detectionScore: number | null;
  recognitionScore: number | null;
  alignment: "none" | "detection" | "recognition-estimate" | "manual";
  readingOrder: number | null;
  angle: number | null;
}
export interface TextSuggestion {
  provider: TextProvider;
  regionId: string | null;
  polygon:
    | [[number, number], [number, number], [number, number]]
    | [[number, number], [number, number], [number, number], [number, number]]
    | [[number, number], [number, number], [number, number], [number, number], [number, number]]
    | [[number, number], [number, number], [number, number], [number, number], [number, number], [number, number]]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | [
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number],
        [number, number]
      ]
    | null;
  role: "text" | "logo" | "watermark" | "artwork" | "unknown";
  transcription: string | null;
  reason: string;
}
export interface TextCorrection {
  regionId: string;
  transcription: string;
  origin: "manual";
}
export interface TextEvidence {
  id: string;
  regionId: string;
  kind: "ink" | "outline" | "shadow" | "background";
  status: "verified" | "unknown";
  origin: "fixture" | "manual" | "source-extractor";
  /**
   * @minItems 0
   * @maxItems 16384
   */
  runs: [number, number][];
}
export interface TextRelation {
  kind: "connected" | "separate" | "hole" | "open-channel";
  /**
   * @minItems 2
   * @maxItems 16
   */
  evidenceIds:
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  status: "verified" | "unknown";
}
export interface SceneAnalysis {
  schemaVersion: 1;
  kind: "scene-analysis";
  sourceHash: string;
  sourceWidth: number;
  sourceHeight: number;
  /**
   * @minItems 4
   * @maxItems 4
   */
  roi: [number, number, number, number];
  goal: string;
  summary: string;
  provider: TextProvider;
  /**
   * @maxItems 12
   */
  regions:
    | []
    | [SceneRegion]
    | [SceneRegion, SceneRegion]
    | [SceneRegion, SceneRegion, SceneRegion]
    | [SceneRegion, SceneRegion, SceneRegion, SceneRegion]
    | [SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion]
    | [SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion]
    | [SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion]
    | [SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion, SceneRegion]
    | [
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion
      ]
    | [
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion
      ]
    | [
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion
      ]
    | [
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion,
        SceneRegion
      ];
  contentHash: string;
}
export interface SceneRegion {
  id: string;
  label: string;
  kind: "subject" | "detail" | "accessory";
  /**
   * @minItems 4
   * @maxItems 4
   */
  box: [number, number, number, number];
  color:
    | "dark"
    | "light"
    | "red"
    | "orange"
    | "yellow"
    | "green"
    | "cyan"
    | "blue"
    | "purple"
    | "pink"
    | "brown"
    | "neutral"
    | "mixed";
  importance: "normal" | "high";
}
